name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  linux-gcc:
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install meson and ninja
        run: pip3 install meson ninja

      - name: Setup meson
        run: meson setup build-gcc
        env:
          CXX: g++
      
      - name: Compile code
        run: meson compile -C build-gcc -v

      - name: Run unit tests
        run: meson test -C build-gcc -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: build-gcc/meson-logs/testlog.txt